2022-05-29 17:52:51,889 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2022-05-29 17:52:51,889 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from C:\Python39\lib\site-packages\instabot\bot\bot.py
2022-05-29 17:52:51,890 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2022-05-29 17:52:52,067 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [429]>
2022-05-29 17:52:52,067 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"Please wait a few minutes before you try again.","status":"fail"}'
2022-05-29 17:52:52,068 - instabot version: 0.117.0 (api) - ERROR - Request returns 429 error!
2022-05-29 17:52:52,273 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [200]>
2022-05-29 17:52:52,759 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [200]>
2022-05-29 17:52:52,954 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [429]>
2022-05-29 17:52:52,954 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"Please wait a few minutes before you try again.","status":"fail"}'
2022-05-29 17:52:52,954 - instabot version: 0.117.0 (api) - ERROR - Request returns 429 error!
2022-05-29 17:52:54,398 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/login/ returned response: <Response [400]>
2022-05-29 17:52:54,398 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"challenge_required","challenge":{"url":"https://i.instagram.com/challenge/AXEYYrqbOO8B9WamEHC-_Um2PyFl01xIwAJsC5gAFp0IyXTfvftXvk_5I1dvQ6mOW0_vYAg/lOe6jvTKuab1w3Ut/","api_path":"/challenge/AXEYYrqbOO8B9WamEHC-_Um2PyFl01xIwAJsC5gAFp0IyXTfvftXvk_5I1dvQ6mOW0_vYAg/lOe6jvTKuab1w3Ut/","hide_webview_header":true,"lock":true,"logout":false,"native_flow":true,"flow_render_type":0},"status":"fail","error_type":"checkpoint_challenge_required"}'
2022-05-29 17:52:54,398 - instabot version: 0.117.0 (api) - ERROR - Request returns 400 error!
2022-05-29 17:52:54,398 - instabot version: 0.117.0 (api) - INFO - Instagram's error message: challenge_required
2022-05-29 17:52:54,398 - instabot version: 0.117.0 (api) - INFO - Error type: checkpoint_challenge_required
2022-05-29 17:52:56,331 - instabot version: 0.117.0 (api_photo) - ERROR - Photo Upload failed with the following response: <Response [403]>
2022-05-29 17:52:56,331 - instabot version: 0.117.0 (bot_photo) - INFO - Photo 'Download/airship_TradingCard (1).jpg' is not uploaded.
2022-05-29 17:53:29,223 - instabot version: 0.117.0 (api_photo) - ERROR - Photo Upload failed with the following response: <Response [403]>
2022-05-29 17:53:29,223 - instabot version: 0.117.0 (bot_photo) - INFO - Photo 'Download/airship_TradingCard (2).jpg' is not uploaded.
2022-05-29 17:54:01,149 - instabot version: 0.117.0 (api_photo) - ERROR - Photo Upload failed with the following response: <Response [403]>
2022-05-29 17:54:01,149 - instabot version: 0.117.0 (bot_photo) - INFO - Photo 'Download/airship_TradingCard (3).jpg' is not uploaded.
2022-05-29 17:54:35,215 - instabot version: 0.117.0 (api_photo) - ERROR - Photo Upload failed with the following response: <Response [403]>
2022-05-29 17:54:35,216 - instabot version: 0.117.0 (bot_photo) - INFO - Photo 'Download/airship_TradingCard.jpg' is not uploaded.
2022-05-29 17:55:07,154 - instabot version: 0.117.0 (api_photo) - ERROR - Photo Upload failed with the following response: <Response [403]>
2022-05-29 17:55:07,154 - instabot version: 0.117.0 (bot_photo) - INFO - Photo 'Download/city_TradingCard (1).jpg' is not uploaded.
