2022-05-29 17:36:24,093 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2022-05-29 17:36:24,093 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from C:\Python39\lib\site-packages\instabot\bot\bot.py
2022-05-29 17:36:24,094 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2022-05-29 17:36:24,268 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [429]>
2022-05-29 17:36:24,268 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"Please wait a few minutes before you try again.","status":"fail"}'
2022-05-29 17:36:24,268 - instabot version: 0.117.0 (api) - ERROR - Request returns 429 error!
2022-05-29 17:36:24,480 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [200]>
2022-05-29 17:36:24,680 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [200]>
2022-05-29 17:36:24,849 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [429]>
2022-05-29 17:36:24,849 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"Please wait a few minutes before you try again.","status":"fail"}'
2022-05-29 17:36:24,849 - instabot version: 0.117.0 (api) - ERROR - Request returns 429 error!
2022-05-29 17:36:27,624 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/login/ returned response: <Response [400]>
2022-05-29 17:36:27,624 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"challenge_required","challenge":{"url":"https://i.instagram.com/challenge/AXG7KX8R-GneJvxDOPMz6qRIrVmnBaSGQLRV_IkHdkJDCMnuzoIf5ivlYqGT_j9TJctL9s0/6qxjfRNiLUO5InZp/","api_path":"/challenge/AXG7KX8R-GneJvxDOPMz6qRIrVmnBaSGQLRV_IkHdkJDCMnuzoIf5ivlYqGT_j9TJctL9s0/6qxjfRNiLUO5InZp/","hide_webview_header":true,"lock":true,"logout":false,"native_flow":true,"flow_render_type":0},"status":"fail","error_type":"checkpoint_challenge_required"}'
2022-05-29 17:36:27,624 - instabot version: 0.117.0 (api) - ERROR - Request returns 400 error!
2022-05-29 17:36:27,627 - instabot version: 0.117.0 (api) - INFO - Instagram's error message: challenge_required
2022-05-29 17:36:27,628 - instabot version: 0.117.0 (api) - INFO - Error type: checkpoint_challenge_required
2022-05-29 17:36:31,106 - instabot version: 0.117.0 (api_photo) - ERROR - Photo Upload failed with the following response: <Response [403]>
2022-05-29 17:36:31,107 - instabot version: 0.117.0 (bot_photo) - INFO - Photo 'Download/airship_TradingCard (1).jpg' is not uploaded.
2022-05-29 17:37:34,103 - instabot version: 0.117.0 (api_photo) - ERROR - Photo Upload failed with the following response: <Response [403]>
2022-05-29 17:37:34,104 - instabot version: 0.117.0 (bot_photo) - INFO - Photo 'Download/airship_TradingCard (2).jpg' is not uploaded.
2022-05-29 17:38:37,274 - instabot version: 0.117.0 (api_photo) - ERROR - Photo Upload failed with the following response: <Response [403]>
2022-05-29 17:38:37,275 - instabot version: 0.117.0 (bot_photo) - INFO - Photo 'Download/airship_TradingCard (3).jpg' is not uploaded.
2022-05-29 17:39:41,168 - instabot version: 0.117.0 (api_photo) - ERROR - Photo Upload failed with the following response: <Response [403]>
2022-05-29 17:39:41,168 - instabot version: 0.117.0 (bot_photo) - INFO - Photo 'Download/airship_TradingCard.jpg' is not uploaded.
